### PR TITLE
Restructure and add CAN firmware

### PR DESCRIPTION
**Pull request by luator**
## Description

Restructure the repository a bit and add the CAN firmware.  The purpose is to have both firmware versions together in one place with a unified structure.  This should make maintenance easier and avoids duplicate documentation for the common parts (e.g. the flash procedure).

Actual changes:

- Remove user_config_f28069m_drv8305 and instead integrate the [user_config_f28069m_drv8305 repository](https://github.com/open-dynamic-robot-initiative/user_config_f28069m_drv8305) as submodule.  They are mostly identical, only change is that the default motor for the single-motor applications changes to be the same as for the dual motor ones.  The separate repository has different branches for different motors, so keeping this as submodule makes it easier to maintain different motor configurations (simply switch to the branch of the desired motor).
- Move `motorware` and `mw_dual_motor_torque_ctrl` to subdirectory `firmware_spi` (and adjust paths in the project config accordingly.  Also removed the "Flash" directory which only contains build files that don't need to be tracked by git.
- Add subdirectory `firmware_can` and add the [CAN firmware](https://github.com/open-dynamic-robot-initiative/mw_dual_motor_torque_ctrl) there.  I kept the whole history of that repo, unfortunately this clutters the history of the pull request a bit...
- Rename the projects by appending `_spi`/`_can`.  This way they can be imported into the same CCS workspace without name collision.

Note: The documentation and READMEs still need to be revised according to the changes.  I didn't do this yet, as I first would like to get your opinion, if it all makes sense like this.

If this is accepted, it deprecates the following repositories:
- https://github.com/open-dynamic-robot-initiative/mw_dual_motor_torque_ctrl
- https://github.com/open-dynamic-robot-initiative/amd_motorware_ext

## Open Questions

- Right now the whole content of this repository is inside a "firmware" folder and there is nothing else at the top level.  Is this needed for some reason or would it be okay to move everything one level up?
- The main license of this repository is currently BSD 2-clause.  Would it be okay if I change this to 3-clause so it is consistent with our other repositories (I think we mostly use 3-clause everywhere).

## How I Tested

Build both SPI and CAN firmware with CCS (both "Release" and "Flash" build).
I did not try actual flashing of a board.

## Todo (before merging)

- [x] Fix motorware patch for SPI: `sw/ide/ccs/cmd/f2806x/f28069M_ram_lnk.cmd` should be renamed to `sw/ide/ccs/cmd/f2806x/F28069M_ram_lnk.cmd` (upper case "F")
- [x] Update documentation and READMEs
- [x] Unify license

### CODE REVIEW

**Comment by luator** [comment]
@jviereck @thomasfla Did you already have time to take a look?
Reviewing this is unfortunately a bit complicated due to all the commits from the history of the CAN firmware.  Maybe you can filter for only the commits starting from [this one](https://github.com/open-dynamic-robot-initiative/udriver_firmware/pull/6/commits/d8695e37b303c6f89a59e4fef3d6c912bf7059f1), ignoring any older commits.

**Comment by thomasfla** [comment]
Hi, thanks for working on it, it sounds like a good solution!
I haven't had time to review the PR yet.

I have a question, does the CAN firmware also works for uDriver v2 where the same SPI is used to configure both DRV ? If yes, how the v1 vs v2 configuration is handled?  

About your questions:
`Right now the whole content of this repository is inside a "firmware" folder and there is nothing else at the top level. Is this needed for some reason or would it be okay to move everything one level up?` 
I think I did this as I tend to have a single repo for **firmware** and **hardware** of electronic board. This is the case for example for the [masterboard](https://github.com/open-dynamic-robot-initiative/master-board) and [powerboard](https://github.com/open-dynamic-robot-initiative/power-board). Currently, we do not included the hardware design file in this repository. So I guess we can remove this folder. Or we might want to rename this repo and include the design files as well. 

`The main license of this repository is currently BSD 2-clause. Would it be okay if I change this to 3-clause so it is consistent with our other repositories (I think we mostly use 3-clause everywhere).`
I personally don't see any problem in changing the license. 

Best,
Thomas.

**Comment by MaximilienNaveau** [comment]
>  think I did this as I tend to have a single repo for **firmware** and **hardware** of electronic board

I really think we should document the different hardware version here.
- Point to the TI board for the CAN version
- Put here the doc of the newly design motor boards.
Hence having an hardware folder here seems a very good idea to me. And I guess that was the idea here.

**Comment by luator** [comment]
@thomasfla 
> I have a question, does the CAN firmware also works for uDriver v2 where the same SPI is used to configure both DRV ? If yes, how the v1 vs v2 configuration is handled?

To be honest, I don't know.  We are using uDriver boards on the TriFinger robots but I'll have to clarify which version it is.  Is there an easy way how I can recognise it?

> About your questions: `Right now the whole content of this repository is inside a "firmware" folder and there is nothing else at the top level. Is this needed for some reason or would it be okay to move everything one level up?` I think I did this as I tend to have a single repo for **firmware** and **hardware** of electronic board. This is the case for example for the [masterboard](https://github.com/open-dynamic-robot-initiative/master-board) and [powerboard](https://github.com/open-dynamic-robot-initiative/power-board). Currently, we do not included the hardware design file in this repository. So I guess we can remove this folder. Or we might want to rename this repo and include the design files as well.

I don't mind adding them here (assuming they are not too big).


@MaximilienNaveau The documentation definitely needs to be updated before merging, I just wanted to wait for general approval of the changes before spending more time on it.

**Comment by MaximilienNaveau** [comment]
> @thomasfla
> 
> > I have a question, does the CAN firmware also works for uDriver v2 where the same SPI is used to configure both DRV ? If yes, how the v1 vs v2 configuration is handled?
> 
> To be honest, I don't know. We are using uDriver boards on the TriFinger robots but I'll have to clarify which version it is. Is there an easy way how I can recognise it?
> 
> > About your questions: `Right now the whole content of this repository is inside a "firmware" folder and there is nothing else at the top level. Is this needed for some reason or would it be okay to move everything one level up?` I think I did this as I tend to have a single repo for **firmware** and **hardware** of electronic board. This is the case for example for the [masterboard](https://github.com/open-dynamic-robot-initiative/master-board) and [powerboard](https://github.com/open-dynamic-robot-initiative/power-board). Currently, we do not included the hardware design file in this repository. So I guess we can remove this folder. Or we might want to rename this repo and include the design files as well.
> 
> I don't mind adding them here (assuming they are not too big).
> 
> @MaximilienNaveau The documentation definitely needs to be updated before merging, I just wanted to wait for general approval of the changes before spending more time on it.

Sure that can wait, I just saying that we should create another PR with this hardware doc and hardware build files.

**Comment by luator** [comment]
FYI: I squashed the history of the CAN firmware so that this PR is not so messy.  The history is still preserved in the original repo if needed.

I am still working on adapting the documentation.

**Comment by MaximilienNaveau** [comment]
Hi, thank you very much for this work!!
I think the folder structure is pretty good.
I am waiting for the documentation to get cleaner before merging the PR.

**Comment by luator** [comment]
@MaximilienNaveau @jviereck @thomasfla I'm finished adapting the documentation, so from my point of few, this is ready to be merged (assuming you approve the changes).

**Comment by luator** [comment]
Of course the documentation can still be improved/extended but I think this is beyond the scope of this PR.

**Comment by luator** [comment]
@jviereck @thomasfla Did you already have time to look at the changes?

**Comment by thomasfla** [comment]
Hi, I'm about to flash some boards, I will do it with the pending PR as a test. 
Sorry for the delay.

**Comment by luator** [comment]
I set up the documentation build, so you can now see the documentation (current state of this branch) at https://open-dynamic-robot-initiative.github.io/udriver_firmware/
Once merged, this will be automatically updated by the added GitHub workflow whenever there is an update on master.

**Comment by thomasfla** [comment]
Thanks for the last changes!

**Pull request merged**
